import { EventType, SocialMediaPostType } from "./types";

const today = new Date();
const y = today.getFullYear();
const m = today.getMonth();
const d = today.getDate();

export const defaultEvents: EventType[] = [
  {
    id: "1",
    title: "Reunión de Equipo",
    start: new Date(y, m, d + 1, 10, 0),
    end: new Date(y, m, d + 1, 11, 30),
    allDay: false,
    color: "default",
    description: "Reunión semanal para revisar el progreso del proyecto",
    location: "Sala de Conferencias A",
    participants: ["Juan Pérez", "María García", "Carlos López"],
  },
  {
    id: "2",
    title: "Presentación Cliente",
    start: new Date(y, m, d + 2, 14, 0),
    end: new Date(y, m, d + 2, 15, 30),
    allDay: false,
    color: "green",
    description: "Presentación del proyecto final al cliente",
    location: "Oficina Principal",
    participants: ["Ana Rodríguez", "Luis Martínez"],
  },
  {
    id: "3",
    title: "Día de Descanso",
    start: new Date(y, m, d + 5),
    end: new Date(y, m, d + 5),
    allDay: true,
    color: "warning",
    description: "Día libre para descansar y recargar energías",
  },
  {
    id: "4",
    title: "Entrenamiento",
    start: new Date(y, m, d + 3, 18, 0),
    end: new Date(y, m, d + 3, 19, 30),
    allDay: false,
    color: "red",
    description: "Sesión de entrenamiento en el gimnasio",
    location: "Gimnasio Central",
    participants: ["Pedro Sánchez"],
  },
  {
    id: "5",
    title: "Cumpleaños María",
    start: new Date(y, m, d + 7),
    end: new Date(y, m, d + 7),
    allDay: true,
    color: "azure",
    description: "Celebración del cumpleaños de María",
    location: "Restaurante El Bueno",
    participants: ["María García", "Juan Pérez", "Ana Rodríguez", "Carlos López"],
  },
  {
    id: "6",
    title: "Deadline Proyecto",
    start: new Date(y, m, d + 10, 17, 0),
    end: new Date(y, m, d + 10, 17, 0),
    allDay: false,
    color: "red",
    description: "Fecha límite para entregar el proyecto final",
  },
  {
    id: "7",
    title: "Conferencia Tech",
    start: new Date(y, m, d + 12, 9, 0),
    end: new Date(y, m, d + 12, 17, 0),
    allDay: true,
    color: "default",
    description: "Conferencia anual de tecnología e innovación",
    location: "Centro de Convenciones",
    participants: ["Equipo de Desarrollo"],
  },
  {
    id: "8",
    title: "Revisión Código",
    start: new Date(y, m, d - 1, 16, 0),
    end: new Date(y, m, d - 1, 17, 0),
    allDay: false,
    color: "green",
    description: "Revisión de código del sprint actual",
    location: "Sala de Desarrollo",
    participants: ["Carlos López", "Ana Rodríguez"],
  },
];

export const defaultSocialMediaPosts: SocialMediaPostType[] = [
  {
    id: "1",
    title: "Lanzamiento del Nuevo Producto",
    content: "¡Estamos emocionados de anunciar el lanzamiento de nuestro nuevo producto! 🚀 Descubre todas las características innovadoras que hemos desarrollado para ti. #NuevoProducto #Innovación #Tech",
    scheduledTime: new Date(y, m, d, 9, 0),
    platforms: ["twitter", "facebook", "linkedin"],
    status: "scheduled",
    hashtags: ["#NuevoProducto", "#Innovación", "#Tech"],
    mentions: ["@techcompany"],
  },
  {
    id: "2",
    title: "Consejos de Marketing Digital",
    content: "5 estrategias efectivas para mejorar tu presencia en redes sociales 📱💡 ¿Cuál es tu favorita? #MarketingDigital #RedesSociales #Estrategia",
    scheduledTime: new Date(y, m, d, 12, 30),
    platforms: ["instagram", "twitter"],
    status: "draft",
    hashtags: ["#MarketingDigital", "#RedesSociales", "#Estrategia"],
  },
  {
    id: "3",
    title: "Behind the Scenes",
    content: "Un vistazo detrás de cámaras de nuestro equipo trabajando en el próximo proyecto 🎬✨ #BehindTheScenes #Equipo #Trabajo",
    scheduledTime: new Date(y, m, d, 15, 0),
    platforms: ["instagram", "tiktok"],
    status: "scheduled",
    hashtags: ["#BehindTheScenes", "#Equipo", "#Trabajo"],
  },
  {
    id: "4",
    title: "Tutorial: Optimización SEO",
    content: "Aprende cómo optimizar tu sitio web para los motores de búsqueda en este tutorial paso a paso 🔍📈 #SEO #Tutorial #Optimización",
    scheduledTime: new Date(y, m, d, 18, 0),
    platforms: ["youtube", "linkedin"],
    status: "published",
    hashtags: ["#SEO", "#Tutorial", "#Optimización"],
  },
  {
    id: "5",
    title: "Feliz Viernes",
    content: "¡Feliz viernes a todos! 🎉 Que tengan un excelente fin de semana lleno de logros y momentos especiales. #FelizViernes #FinDeSemana #Motivación",
    scheduledTime: new Date(y, m, d, 20, 30),
    platforms: ["facebook", "twitter", "instagram"],
    status: "draft",
    hashtags: ["#FelizViernes", "#FinDeSemana", "#Motivación"],
  },
  {
    id: "6",
    title: "Análisis de Tendencias",
    content: "Las tendencias más importantes en tecnología para 2024 📊🔮 ¿Estás preparado para el futuro? #Tendencias #Tecnología #2024",
    scheduledTime: new Date(y, m, d + 1, 10, 0),
    platforms: ["linkedin", "twitter"],
    status: "scheduled",
    hashtags: ["#Tendencias", "#Tecnología", "#2024"],
  },
  {
    id: "7",
    title: "Receta del Día",
    content: "Deliciosa receta de pasta casera que te encantará 🍝👨‍🍳 ¡Comparte tu versión! #Receta #Pasta #Cocina",
    scheduledTime: new Date(y, m, d + 1, 13, 0),
    platforms: ["instagram", "pinterest"],
    status: "draft",
    hashtags: ["#Receta", "#Pasta", "#Cocina"],
  },
  {
    id: "8",
    title: "Consejos de Productividad",
    content: "3 técnicas simples para aumentar tu productividad en el trabajo ⚡💼 ¿Cuál vas a probar hoy? #Productividad #Trabajo #Consejos",
    scheduledTime: new Date(y, m, d + 1, 16, 30),
    platforms: ["twitter", "linkedin"],
    status: "scheduled",
    hashtags: ["#Productividad", "#Trabajo", "#Consejos"],
  },
]; 